/// Flutter icons DarwinFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DarwinFont
///      fonts:
///       - asset: fonts/DarwinFont.ttf
///
///
///
import 'package:flutter/widgets.dart';

///
/// Main Icon Font Class
///
/// used for  icons
class DarwinFont {
  DarwinFont._();

  static const _kFontFam = 'DarwinFont';

  static const IconData bell = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData calendar = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cancel = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData chevronDown = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chevronLeft = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData chevronRight = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData emojiHappy = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData emojiOk = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData emojiSad = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData emojiTooHappy = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData emojiTooSad = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData files = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData gps = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData layers = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData checkRound = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData map = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData mic = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData moreHorizontal =
      IconData(0xe817, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData play = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData record = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData refresh = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData signature = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData sort = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData starOutline = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData starSolid = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData stop = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData undo = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData video = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData logoAnimatable =
      IconData(0xe826, fontFamily: _kFontFam);
  static const IconData logo = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData starSolidHalf = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData roundRing = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData cancelRound = IconData(0xe82a, fontFamily: _kFontFam);
}
